services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://103.72.97.222:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=123456789@