supported_cities = [
    "Ho Chi Minh City",
]

supported_districts = ["District 1",
                        "District 2",
                        "District 3",
                        "District 4",
                        "District 5",
                        "District 6",
                        "District 7",
                        "District 8",
                        "District 9",
                        "District 10",
                        "District 11",
                        "District 12",
                        "Binh Thanh District",
                        "Go Vap District",
                        "Tan Binh District",
                        "Tan Phu District",
                        "Phu Nhuan District",
                        "Binh Tan District",
                        "Thu Duc City",
                        "Nha Be District",
                        "Binh Chanh District",
                        "Can Gio District",
                        "Cu Chi District",
                        "Hoc Mon District"]

supported_districts_vi = ["Quận 1",
                          "Quận 2",
                          "Quận 3",
                          "Quận 4",
                          "Quận 5",
                          "Quận 6",
                          "Quận 7",
                          "Quận 8",
                          "Quận 9",
                          "Quận 10",
                          "Quận 11",
                          "Quận 12",
                          "Quận Bình Thạnh",
                          "Quận Gò Vấp",
                          "Quận Tân Bình",
                          "Quận Tân Phú",
                          "Quận Phú Nhuận",
                          "Quận Bình Tân",
                          "Thành phố Thủ Đức",
                          "Huyện Nhà Bè",
                          "Huyện Bình Chánh",
                          "Huyện Cần Giờ",
                          "Huyện Củ Chi",
                          "Huyện Hóc Môn"]

covered_districts = [""]

# Ánh xạ tên quận sang các quận lân cận (ví dụ, bạn cần điền đúng dữ liệu thực tế)
district_neighbors = {
    "District 1": ["District 2", "District 3", "Phu Nhuan District", "District 4", "Binh Thanh District", "District 5", "District 10", "District 7", "District 8"],
    "District 2": ["District 1", "District 3", "Binh Thanh District", "Thu Duc City", "District 9", "District 4", "District 7"],
    "District 3": ["District 1", "Phu Nhuan District", "District 10", "Binh Thanh District", "Tan Binh District", "District 5", "District 11", "District 4", "Go Vap District", "District 11"],
    "District 4": ["District 1", "District 2", "District 7", "District 5", "District 8", "District 3", "District 10", "Binh Thanh District", "Binh Chanh District"],
    "District 5": ["District 1", "District 7", "District 3", "District 4", "District 8", "District 6", "District 10", "District 11", "Tan Phu District", "Tan Binh District", "Phu Nhuan District", "Binh Chanh District"],
    "District 6": ["District 5", "District 8", "District 10", "District 11", "Binh Tan District", "Tan Phu District", "Tan Binh District", "District 1", "Binh Chanh District"],
    "District 7": ["District 1", "District 2", "District 4", "District 8", "Nha Be District", "Binh Thanh District", "District 5", "Binh Chanh District", "District 10"],
    "District 8": ["District 4", "District 5", "District 6", "District 1", "District 11", "District 7", "Binh Tan District", "Nha Be District", "Binh Thanh District", "District 10", "Tan Phu District", "Nha Be District"],
    "District 9": ["District 2", "Thu Duc City", "Binh Thanh District"],
    "District 10": ["District 1", "District 3", "District 5", "District 6", "Binh Thanh District", "Tan Binh District", "Phu Nhuan District", "District 11", "Tan Phu District", "District 8", "District 4"],
    "District 11": ["District 1", "District 3", "District 5", "District 6", "Binh Thanh District", "Tan Binh District", "Phu Nhuan District", "District 10", "Binh Tan District", "Tan Phu District"],
    "District 12": ["Thu Duc City", "Binh Thanh District", "Go Vap District", "Tan Binh District", "Tan Phu District", "Binh Tan District", "Hoc Mon District", "Cu Chi District", "Binh Chanh District"],
    "Binh Thanh District": ["District 1", "District 2", "District 3", "District 4", "District 5", "District 9", "District 10", "Thu Duc City", "Go Vap District", "Tan Binh District", "Phu Nhuan District"],
    "Go Vap District": ["District 3", "District 12", "Binh Thanh District", "Tan Binh District", "Tan Phu District", "Phu Nhuan District", "Thu Duc City", "District 1"],
    "Tan Binh District": ["District 1", "District 3", "District 5", "District 6", "District 10", "District 11", "District 12", "Binh Thanh District", "Go Vap District", "Tan Phu District", "Phu Nhuan District"],
    "Tan Phu District": ["District 1", "District 3", "District 5", "District 6", "District 12", "Binh Tan District", "District 10", "District 11", "Go Vap District", "Tan Binh District", "Phu Nhuan District"],
    "Phu Nhuan District": ["District 1", "District 3", "District 5", "District 4", "District 10", "District 11", "Binh Thanh District", "Go Vap District", "Tan Binh District", "Tan Phu District"],
    "Binh Tan District": ["District 5", "District 6", "District 11", "District 8", "District 10", "Tan Phu District", "Tan Binh District", "Hoc Mon District", "District 12", "Binh Chanh District"],
    "Thu Duc City": ["District 2", "District 9", "Binh Thanh District", "District 12", "Go Vap District"],
    "Nha Be District": ["District 7", "District 8", "Binh Thanh District", "District 4", "District 5", "Binh Chanh District"],
    "Binh Chanh District": ["District 5", "District 6", "District 7", "District 8", "Binh Tan District", "Nha Be District", "Cu Chi District", "Hoc Mon District"],
    "Can Gio District": ["District 7", "Nha Be District", "Binh Chanh District"],
    "Cu Chi District": ["District 12", "Binh Chanh District", "Hoc Mon District"],
    "Hoc Mon District": ["District 12", "Binh Tan District", "Binh Chanh District", "Cu Chi District", "Go Vap District", "Tan Phu District", "Tan Binh District"],
    # Đã chuyển các key và value tiếng Việt sang tiếng Anh
    "Quận 1": ["Quận 2", "Quận 3", "Quận Phú Nhuận", "Quận 4", "Quận Bình Thạnh", "Quận 5", "Quận 10", "Quận 7", "Quận 8"],
    "Quận 2": ["Quận 1", "Quận 3", "Quận Bình Thạnh", "Thành phố Thủ Đức", "Quận 9", "Quận 4", "Quận 7"],
    "Quận 3": ["Quận 1", "Quận Phú Nhuận", "Quận 10", "Quận Bình Thạnh", "Quận Tân Bình", "Quận 5", "Quận 11", "Quận 4", "Quận Gò Vấp", "Quận 11"],
    "Quận 4": ["Quận 1", "Quận 2", "Quận 7", "Quận 5", "Quận 8", "Quận 3", "Quận 10", "Quận Bình Thạnh", "Huyện Bình Chánh"],
    "Quận 5": ["Quận 1", "Quận 7", "Quận 3", "Quận 4", "Quận 8", "Quận 6", "Quận 10", "Quận 11", "Quận Tân Phú", "Quận Tân Bình", "Quận Phú Nhuận", "Huyện Bình Chánh"],
    "Quận 6": ["Quận 5", "Quận 8", "Quận 10", "Quận 11", "Quận Bình Tân", "Quận Tân Phú", "Quận Tân Bình", "Quận 1", "Huyện Bình Chánh"],
    "Quận 7": ["Quận 1", "Quận 2", "Quận 4", "Quận 8", "Huyện Nhà Bè", "Quận Bình Thanh", "Quận 5", "Huyện Bình Chánh", "Quận 10"],
    "Quận 8": ["Quận 4", "Quận 5", "Quận 6", "Quận 1", "Quận 11", "Quận 7", "Quận Bình Tân", "Huyện Nhà Bè", "Quận Bình Thanh", "Quận 10", "Quận Tân Phú", "Huyện Nhà Bè"],
    "Quận 9": ["Quận 2", "Thành phố Thủ Đức", "Quận Bình Thanh"],
    "Quận 10": ["Quận 1", "Quận 3", "Quận 5", "Quận 6", "Quận Bình Thanh", "Quận Tân Bình", "Quận Phú Nhuận", "Quận 11", "Quận Tân Phú", "Quận 8", "Quận 4"],
    "Quận 11": ["Quận 1", "Quận 3", "Quận 5", "Quận 6", "Quận Bình Thanh", "Quận Tân Bình", "Quận Phú Nhuận", "Quận 10", "Quận Bình Tân", "Quận Tân Phú"],
    "Quận 12": ["Thành phố Thủ Đức", "Quận Bình Thanh", "Quận Gò Vấp", "Quận Tân Bình", "Quận Tân Phú", "Quận Bình Tân", "Huyện Hóc Môn", "Huyện Củ Chi", "Huyện Bình Chánh"],
    "Quận Bình Thạnh": ["Quận 1", "Quận 2", "Quận 3", "Quận 4", "Quận 5", "Quận 9", "Quận 10", "Thành phố Thủ Đức", "Quận Gò Vấp", "Quận Tân Bình", "Phú Nhuận"],
    "Quận Gò Vấp": ["Quận 3", "Quận 12", "Quận Bình Thạnh", "Quận Tân Bình", "Quận Tân Phú", "Phú Nhuận", "Thành phố Thủ Đức", "Quận 1"],
    "Quận Tân Bình": ["Quận 1", "Quận 3", "Quận 5", "Quận 6", "Quận 10", "Quận 11", "Quận 12", "Quận Bình Thanh", "Quận Gò Vấp", "Quận Tân Phú", "Phú Nhuận"],
    "Quận Tân Phú": ["Quận 1", "Quận 3", "Quận 5", "Quận 6", "Quận 12", "Quận Bình Tân", "Quận 10", "Quận 11", "Quận Gò Vấp", "Quận Tân Bình", "Phú Nhuận"],
    "Quận Phú Nhuận": ["Quận 1", "Quận 3", "Quận 5", "Quận 4", "Quận 10", "Quận 11", "Quận Bình Thanh", "Quận Gò Vấp", "Quận Tân Bình", "Quận Tân Phú"],
    "Quận Bình Tân": ["Quận 5", "Quận 6", "Quận 11", "Quận 8", "Quận 10", "Quận Tân Phú", "Quận Tân Bình", "Huyện Hóc Môn", "Quận 12", "Huyện Bình Chánh"],
    "Thành phố Thủ Đức": ["Quận 2", "Quận 9", "Quận Bình Thanh", "Quận 12", "Quận Gò Vấp"],
    "Huyện Nhà Bè": ["Quận 7", "Quận 8", "Quận Bình Thanh", "Huyện Bình Chánh"],
    "Huyện Bình Chánh": ["Quận 5", "Quận 6", "Quận 7", "Quận 8", "Quận Bình Tân", "Huyện Nhà Bè", "Huyện Cần Giờ", "Huyện Củ Chi"],
    "Huyện Cần Giờ": ["Quận 7", "Huyện Nhà Bè", "Huyện Bình Chánh"],
    "Huyện Củ Chi": ["Quận 12", "Huyện Bình Chánh", "Huyện Hóc Môn"],
    "Huyện Hóc Môn": ["Quận 12", "Quận Bình Tân", "Huyện Bình Chánh", "Huyện Củ Chi", "Quận Gò Vấp", "Quận Tân Phú", "Quận Tân Bình"],
}

def get_neighbor_districts(district_name):
    """Trả về mảng các quận bao quanh quận truyền vào."""
    return district_neighbors.get(district_name, [])
def get_supported_districts():
    """Trả về danh sách các quận được hỗ trợ."""
    return supported_districts